---

- name: Add repository source
  apt_repository:
    repo: deb http://repozytorium.mati75.eu/raspbian jessie-backports main contrib non-free
    state: present

- name: execute apt-key update
  command: apt-key update

- name: Update apt cache
  apt: update_cache=yes

- name: gpg add key
  apt_key:
    keyserver: pgpkeys.mit.edu
    id: CCD91D6111A06851

- name: execute apt-key update
  shell: apt-get update

- name: install php-fpm
  apt:
    state: present
    name:
      - sqlite3
      - php7.3-cli
      - php7.3-curl
      - php7.3-fpm
      - php7.3-intl
      - php7.3-json
      - php7.3-dom
      - php7.3-sqlite3
      - php7.3-mbstring
      - php7.3-mysql

- name: ensure php7.3-fpm cgi.fix_pathinfo=0
  lineinfile: dest='{{item}}' regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
  with_items:
    - /etc/php/7.3/fpm/php.ini
    - /etc/php/7.3/cli/php.ini
  notify:
    - restart php-fpm
    - restart nginx

- name: enable php7.3 mcrypt module
  shell: phpenmod mcrypt
  args:
    creates: /etc/php/7.3/cli/conf.d/20-mcrypt.ini
  notify: restart php-fpm

- name: enable php7.3 dom module
  shell: phpenmod dom
  args:
    creates: /etc/php/7.3/cli/conf.d/20-dom.ini
  notify: restart php-fpm

- name: enable php7.3 mbstring module
  shell: phpenmod mbstring
  args:
    creates: /etc/php/7.3/cli/conf.d/20-mbstring.ini

- name: Creates directory
  file: path=/var/www/html state=directory

- name: Copy phpinfo file
  template: src=phpinfo.php dest=/var/www/html/phpinfo.php
